language: node_js
node_js:
- "10.14"
deploy:
- provider: script
  verbose: true
  script: git fetch --unshallow && git push https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@awaywego.scm.azurewebsites.net:443/awaywego.git HEAD:refs/heads/master
  on: master
- provider: script
  verbose: true
  script: git fetch --unshallow && git push https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@testawaywego.scm.azurewebsites.net:443/testawaywego.git HEAD:refs/heads/development
  on: development