language: node_js
node_js:
- "10.14"
deploy:
- provider: script
  script: git fetch --unshallow && git push -f https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@awaywego.scm.azurewebsites.net:443/awaywego.git HEAD:refs/heads/master
  on: master
before script: 
  - npm install coveralls --save-dev
script:
  - npm run coveralls
after_success:
  - coveralls-lcov coverage/lcov.info
  