language: node_js
node_js:
- "10.14"
deploy:
- provider: azure_web_apps
  on: master
before script: 
  - npm install coveralls --save-dev
script:
  - npm run coveralls
after_success:
  - coveralls-lcov coverage/lcov.info